# Generated by Django 4.1.5 on 2023-04-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('context', models.TextField(blank=True)),
                ('is_released', models.BooleanField(default=True)),
            ],
        ),
    ]
